/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pluralsight.reactive.model.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DocumentLockedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 825069559680352095L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentLockedEvent\",\"namespace\":\"com.pluralsight.reactive.model.domain\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"description\":\"The event id.\"},{\"name\":\"principal\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"description\":\"The principal's name.\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"description\":\"The document name that was submitted.\"},{\"name\":\"eTag\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"description\":\"The document reference.\"},{\"name\":\"createdAt\",\"type\":\"long\",\"description\":\"The time of the cancellation.\"},{\"name\":\"errorCode\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"description\":\"The error code, if an error occurred.\"},{\"name\":\"errorMessage\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"description\":\"The error message, if an error occurred.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DocumentLockedEvent> ENCODER =
      new BinaryMessageEncoder<DocumentLockedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentLockedEvent> DECODER =
      new BinaryMessageDecoder<DocumentLockedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentLockedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentLockedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentLockedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DocumentLockedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentLockedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentLockedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentLockedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentLockedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String id;
  @Deprecated public java.lang.String principal;
  @Deprecated public java.lang.String name;
  @Deprecated public java.lang.String eTag;
  @Deprecated public long createdAt;
  @Deprecated public java.lang.String errorCode;
  @Deprecated public java.lang.String errorMessage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentLockedEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param principal The new value for principal
   * @param name The new value for name
   * @param eTag The new value for eTag
   * @param createdAt The new value for createdAt
   * @param errorCode The new value for errorCode
   * @param errorMessage The new value for errorMessage
   */
  public DocumentLockedEvent(java.lang.String id, java.lang.String principal, java.lang.String name, java.lang.String eTag, java.lang.Long createdAt, java.lang.String errorCode, java.lang.String errorMessage) {
    this.id = id;
    this.principal = principal;
    this.name = name;
    this.eTag = eTag;
    this.createdAt = createdAt;
    this.errorCode = errorCode;
    this.errorMessage = errorMessage;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return principal;
    case 2: return name;
    case 3: return eTag;
    case 4: return createdAt;
    case 5: return errorCode;
    case 6: return errorMessage;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: principal = (java.lang.String)value$; break;
    case 2: name = (java.lang.String)value$; break;
    case 3: eTag = (java.lang.String)value$; break;
    case 4: createdAt = (java.lang.Long)value$; break;
    case 5: errorCode = (java.lang.String)value$; break;
    case 6: errorMessage = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'principal' field.
   * @return The value of the 'principal' field.
   */
  public java.lang.String getPrincipal() {
    return principal;
  }


  /**
   * Sets the value of the 'principal' field.
   * @param value the value to set.
   */
  public void setPrincipal(java.lang.String value) {
    this.principal = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'eTag' field.
   * @return The value of the 'eTag' field.
   */
  public java.lang.String getETag() {
    return eTag;
  }


  /**
   * Sets the value of the 'eTag' field.
   * @param value the value to set.
   */
  public void setETag(java.lang.String value) {
    this.eTag = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'errorCode' field.
   * @return The value of the 'errorCode' field.
   */
  public java.lang.String getErrorCode() {
    return errorCode;
  }


  /**
   * Sets the value of the 'errorCode' field.
   * @param value the value to set.
   */
  public void setErrorCode(java.lang.String value) {
    this.errorCode = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.String getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.errorMessage = value;
  }

  /**
   * Creates a new DocumentLockedEvent RecordBuilder.
   * @return A new DocumentLockedEvent RecordBuilder
   */
  public static com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder newBuilder() {
    return new com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder();
  }

  /**
   * Creates a new DocumentLockedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentLockedEvent RecordBuilder
   */
  public static com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder newBuilder(com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder other) {
    if (other == null) {
      return new com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder();
    } else {
      return new com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder(other);
    }
  }

  /**
   * Creates a new DocumentLockedEvent RecordBuilder by copying an existing DocumentLockedEvent instance.
   * @param other The existing instance to copy.
   * @return A new DocumentLockedEvent RecordBuilder
   */
  public static com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder newBuilder(com.pluralsight.reactive.model.domain.DocumentLockedEvent other) {
    if (other == null) {
      return new com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder();
    } else {
      return new com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentLockedEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentLockedEvent>
    implements org.apache.avro.data.RecordBuilder<DocumentLockedEvent> {

    private java.lang.String id;
    private java.lang.String principal;
    private java.lang.String name;
    private java.lang.String eTag;
    private long createdAt;
    private java.lang.String errorCode;
    private java.lang.String errorMessage;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.principal)) {
        this.principal = data().deepCopy(fields()[1].schema(), other.principal);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.eTag)) {
        this.eTag = data().deepCopy(fields()[3].schema(), other.eTag);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.errorCode)) {
        this.errorCode = data().deepCopy(fields()[5].schema(), other.errorCode);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[6].schema(), other.errorMessage);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentLockedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pluralsight.reactive.model.domain.DocumentLockedEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.principal)) {
        this.principal = data().deepCopy(fields()[1].schema(), other.principal);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.eTag)) {
        this.eTag = data().deepCopy(fields()[3].schema(), other.eTag);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.errorCode)) {
        this.errorCode = data().deepCopy(fields()[5].schema(), other.errorCode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[6].schema(), other.errorMessage);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'principal' field.
      * @return The value.
      */
    public java.lang.String getPrincipal() {
      return principal;
    }


    /**
      * Sets the value of the 'principal' field.
      * @param value The value of 'principal'.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder setPrincipal(java.lang.String value) {
      validate(fields()[1], value);
      this.principal = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'principal' field has been set.
      * @return True if the 'principal' field has been set, false otherwise.
      */
    public boolean hasPrincipal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'principal' field.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder clearPrincipal() {
      principal = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'eTag' field.
      * @return The value.
      */
    public java.lang.String getETag() {
      return eTag;
    }


    /**
      * Sets the value of the 'eTag' field.
      * @param value The value of 'eTag'.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder setETag(java.lang.String value) {
      validate(fields()[3], value);
      this.eTag = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'eTag' field has been set.
      * @return True if the 'eTag' field has been set, false otherwise.
      */
    public boolean hasETag() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'eTag' field.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder clearETag() {
      eTag = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder setCreatedAt(long value) {
      validate(fields()[4], value);
      this.createdAt = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder clearCreatedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorCode' field.
      * @return The value.
      */
    public java.lang.String getErrorCode() {
      return errorCode;
    }


    /**
      * Sets the value of the 'errorCode' field.
      * @param value The value of 'errorCode'.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder setErrorCode(java.lang.String value) {
      validate(fields()[5], value);
      this.errorCode = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'errorCode' field has been set.
      * @return True if the 'errorCode' field has been set, false otherwise.
      */
    public boolean hasErrorCode() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'errorCode' field.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder clearErrorCode() {
      errorCode = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[6], value);
      this.errorMessage = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public com.pluralsight.reactive.model.domain.DocumentLockedEvent.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentLockedEvent build() {
      try {
        DocumentLockedEvent record = new DocumentLockedEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.principal = fieldSetFlags()[1] ? this.principal : (java.lang.String) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.eTag = fieldSetFlags()[3] ? this.eTag : (java.lang.String) defaultValue(fields()[3]);
        record.createdAt = fieldSetFlags()[4] ? this.createdAt : (java.lang.Long) defaultValue(fields()[4]);
        record.errorCode = fieldSetFlags()[5] ? this.errorCode : (java.lang.String) defaultValue(fields()[5]);
        record.errorMessage = fieldSetFlags()[6] ? this.errorMessage : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentLockedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentLockedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentLockedEvent>
    READER$ = (org.apache.avro.io.DatumReader<DocumentLockedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.principal);

    out.writeString(this.name);

    out.writeString(this.eTag);

    out.writeLong(this.createdAt);

    if (this.errorCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.errorCode);
    }

    if (this.errorMessage == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.errorMessage);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.principal = in.readString();

      this.name = in.readString();

      this.eTag = in.readString();

      this.createdAt = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.errorCode = null;
      } else {
        this.errorCode = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.errorMessage = null;
      } else {
        this.errorMessage = in.readString();
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.principal = in.readString();
          break;

        case 2:
          this.name = in.readString();
          break;

        case 3:
          this.eTag = in.readString();
          break;

        case 4:
          this.createdAt = in.readLong();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.errorCode = null;
          } else {
            this.errorCode = in.readString();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.errorMessage = null;
          } else {
            this.errorMessage = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










