# Starting docker compose for module 5
#
# docker-compose -f docker-compose.m05.yml up zookeeper broker schema-registry
# docker-compose -f docker-compose.m05.yml up document-service translation-service

version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: "250M"
  broker:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: "1024M"
  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: "250M"
  document-service:
    image: com.pluralsight.reactive/document-service:latest
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: m05
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: "250M"
  translation-service:
    image: com.pluralsight.reactive/translation-service:latest
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: m05
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: "250M"